---
- name: Ensure controllers
  hosts: localhost
  connection: local
  module_defaults:
    group/hetzner.hcloud.all:
      api_token: "{{ vault_hetzner_token }}"
  vars:
    controllers:
      - name: ctrl-1
        ip: 10.0.0.11
      - name: ctrl-2
        ip: 10.0.0.12
      - name: ctrl-3
        ip: 10.0.0.13

  tasks:

    - name: Ensure LB
      hetzner.hcloud.load_balancer:
        name: Ingress-LB
        load_balancer_type: lb11
        algorithm: round_robin
        location: hel1
        state: present
      register: lb_result

    - name: Add LB to controller network
      hetzner.hcloud.load_balancer_network:
        network: ocp-network
        load_balancer: Ingress-LB
        ip: 10.0.0.2
        state: present

    - name: Forward http ingress
      hetzner.hcloud.load_balancer_service:
        load_balancer: Ingress-LB
        protocol: http
        listen_port: 80
        state: present

    - name: Forward https ingress
      hetzner.hcloud.load_balancer_service:
        load_balancer: Ingress-LB
        protocol: tcp
        listen_port: 443
        destination_port: 443
        state: present

    - name: Forward api ingress
      hetzner.hcloud.load_balancer_service:
        load_balancer: Ingress-LB
        protocol: tcp
        listen_port: 6443
        destination_port: 6443
        state: present

    - name: Forward machine config ingress
      hetzner.hcloud.load_balancer_service:
        load_balancer: Ingress-LB
        protocol: tcp
        listen_port: 22623
        destination_port: 22623
        state: present

    - name: Add controllers to LB
      hetzner.hcloud.load_balancer_target:
        type: label_selector
        load_balancer: Ingress-LB
        label_selector: role=controller
        use_private_ip: true
        state: present

    - name: Create a placement group for controllers
      hetzner.hcloud.placement_group:
        name: controllers
        type: spread
        labels:
          role: controller
        state: present

    - name: Create controllers
      hetzner.hcloud.server:
        name: "{{ item.name }}"
        # server_type: cpx11
        server_type: cpx41
        datacenter: hel1-dc2
        image: centos-stream-10
        ssh_keys:
          - hetzner-admin
        enable_ipv4: false
        enable_ipv6: false
        placement_group: controllers
        labels:
          role: controller
        state: created
      loop: "{{ controllers }}"

    - name: Attach controllers to subnetwork
      hetzner.hcloud.server_network:
        network: ocp-network
        server: "{{ item.name }}"
        ip: "{{ item.ip }}"
        state: present
      loop: "{{ controllers }}"

    - name: Start servers
      hetzner.hcloud.server:
        name: "{{ item.name }}"
        state: started
      loop: "{{ controllers }}"

    - name: Refresh inventory to get access to servers
      meta: refresh_inventory

    - name: Write inventory file for guests
      ansible.builtin.copy:
        dest: proxy-inventory.yml
        content: |
          [proxy]
          bastion ansible_ssh_host={{ hostvars[groups['role_bastion'][0]]['hcloud_ipv4'] }}

          [controllers]
          ctrl-1 ansible_ssh_host={{ hostvars[groups['role_controller'][0]]['hcloud_private_networks'][0]['ip'] }}
          ctrl-2 ansible_ssh_host={{ hostvars[groups['role_controller'][1]]['hcloud_private_networks'][0]['ip'] }}
          ctrl-3 ansible_ssh_host={{ hostvars[groups['role_controller'][2]]['hcloud_private_networks'][0]['ip'] }}

          [controllers:vars]
          ansible_ssh_common_args='-o ProxyCommand="ssh -p 22 -W %h:%p -q root@"{{ hostvars[groups['role_bastion'][0]]['hcloud_ipv4'] }}'

    - debug:
        msg:
          - "bastion at: {{ hostvars[groups['role_bastion'][0]]['hcloud_ipv4'] }}"
          - "LB {{ lb_result.hcloud_load_balancer.name }} at: {{ lb_result.hcloud_load_balancer.ipv4_address }}"
          - "ctrl-1 private at: {{ hostvars[groups['role_controller'][0]]['hcloud_private_networks'][0]['ip'] }}"
          - "ctrl-2 private at: {{ hostvars[groups['role_controller'][1]]['hcloud_private_networks'][0]['ip'] }}"
          - "ctrl-3 private at: {{ hostvars[groups['role_controller'][2]]['hcloud_private_networks'][0]['ip'] }}"
