---
- name: Ensure controllers
  hosts: role_controller
  module_defaults:
    group/hetzner.hcloud.all:
      api_token: "{{ vault_hetzner_token }}"
  vars:
    ansible_ssh_user: root

  tasks:

    - name: Create config snipplet dir
      delegate_to: localhost
      ansible.builtin.file:
        path: net-configs
        state: directory

    - name: Create config file snipplet for the agent
      delegate_to: localhost
      ansible.builtin.copy:
        dest: "net-configs/agent-config-{{ ansible_hostname }}.yaml"
        content: |2
          - hostname: {{ ansible_hostname }} 
            interfaces:
            - name: enp7s0
              macAddress: {{ ansible_eth0.macaddress }}
            networkConfig: 
              interfaces:
              - name: enp7s0
                type: ethernet
                state: up
                mac-address: {{ ansible_eth0.macaddress }} 
                mtu: 1450
                ipv4:
                  enabled: true
                  address:
                  - ip: {{ ansible_eth0.ipv4.address }}
                    prefix-length: 32
                  dhcp: false
              dns-resolver:
                config:
                  server:
                  - 185.12.64.1
                  - 185.12.64.2
              routes:
                config:
                # hetzner network architecture at:
                # https://docs.hetzner.com/cloud/networks/technical-concepts/architecture
                # bridge via device
                - destination: 10.0.0.1/32
                  next-hop-address: 10.0.0.1
                  next-hop-interface: enp7s0
                  table-id: 254
                # subnet and vswitch net via bridge
                - destination: 10.0.0.0/22
                  next-hop-address: 10.0.0.1
                  next-hop-interface: enp7s0
                  table-id: 254
                # default via bastion
                - destination: 0.0.0.0/0
                  next-hop-address: 10.0.0.1
                  next-hop-interface: enp7s0
                  table-id: 254
