---
- name: Ensure controllers
  hosts: role_controller
  module_defaults:
    group/hetzner.hcloud.all:
      api_token: "{{ vault_hetzner_token }}"
  vars:
    ansible_ssh_user: root

  tasks:

    - debug:
        msg: 
          - "ip: {{ ansible_eth0.ipv4.address }} - mac: {{ ansible_eth0.macaddress }}"

    - name: Create config snipplet dir
      delegate_to: localhost
      ansible.builtin.file:
        path: net-configs
        state: directory

    - name: Create config file snipplet for the agent
      delegate_to: localhost
      ansible.builtin.copy:
        dest: "net-configs/agent-config-{{ ansible_hostname }}.yaml"
        content: |2
          - hostname: {{ ansible_hostname }} 
            interfaces:
            - name: enp1s0
              macAddress: {{ ansible_eth0.macaddress }}
            networkConfig: 
              interfaces:
              - name: enp1s0
                type: ethernet
                state: up
                mac-address: {{ ansible_eth0.macaddress }} 
                mtu: 1500
                ipv4:
                  enabled: true
                  address:
                  - ip: {{ ansible_eth0.ipv4.address }}
                    prefix-length: 32
                  dhcp: false
              dns-resolver:
                config:
                  server:
                  - 185.12.64.1
                  - 185.12.64.2
                  # - 2a01:4ff:ff00::add:1
                  # - 2a01:4ff:ff00::add:2
              routes:
                config:
                # hetzner network architecture at:
                # https://docs.hetzner.com/cloud/networks/technical-concepts/architecture
                # default via hetzner fixed ip
                - destination: 0.0.0.0/0
                  next-hop-address: 172.31.1.1
                  next-hop-interface: enp1s0
                  table-id: 254

